flask_app/cart/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, Regexp, URL


from flask_app.models import CartItem


class AddToCartForm(FlaskForm):
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    submit = SubmitField('Add to Cart')

flask_app/cart/routes.py
from flask import render_template, url_for, redirect, request, current_app, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import CartItem
from flask_app.cart.forms import AddToCartForm
from flask_login import current_user

cart = Blueprint('cart', __name__)

@cart.route("/cart", methods=['GET'])
@login_required
def user_cart():
    #form = PurchaseForm()

    #if form.validate_on_submit():
    #   return redirect(url_for('users.account'))
    user_cart_listings = current_user.cart
    print(user_cart_listings)
    return render_template('cart.html', title='Cart', cart=user_cart_listings)

@cart.route("/remove_from_cart/<listing_id>")
def remove_from_cart(listing_id):
    cart_item = CartItem.query.filter_by(id=listing_id).first_or_404()
    db.session.delete(cart_item)
    db.session.commit()
    return redirect(url_for('cart.user_cart'))


@cart.route("/cart/<listing_id>")
@login_required
def add_to_cart(listing_id):
   cart = CartItem(listing_id=listing_id, user_id=current_user.id)
   db.session.add(cart)
   db.session.commit()
   return redirect(url_for('cart.user_cart'))

flask_app/listings/routes.py
from flask import render_template, url_for, redirect, request, current_app, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import Listing
from flask_app.listings.forms import CreateForm, ManageForm


listings = Blueprint('listings', __name__)

@listings.route("/create-listing", methods=['GET', 'POST'])
@login_required
def create_listing():
    form = CreateForm()

    if form.validate_on_submit():
        listing = Listing(title=form.item_name.data, description=form.item_desc.data, price_in_pennies=form.price.data, picture_url=form.item_picture_url.data, user_id=current_user.id)
        db.session.add(listing)
        db.session.commit()

        return redirect(url_for('users.account'))
    
    return render_template('create_listing.html', title='Create Listing', form=form)

@listings.route("/manage-listing/<listing_id>", methods=['GET', 'POST'])
@login_required
def manage_listing(listing_id):
    form = ManageForm()
    listing = Listing.query.filter_by(id=listing_id).first_or_404()
    if form.validate_on_submit():
        listing.title = form.item_name.data
        listing.description = form.item_desc.data
        listing.price_in_pennies = form.price.data
        listing.picture_url = form.item_picture_url.data
        db.session.commit()
    elif request.method == 'GET':
        form.item_name.data = listing.title
        form.item_desc.data = listing.description
        form.price.data = listing.price_in_pennies
        form.item_picture_url.data = listing.picture_url

    return render_template('manage_listing.html', title='Manage Listing', form=form, listing=listing)  

flask_app/main/routes.py
from flask import render_template, Blueprint, request, current_app, redirect, url_for
from flask_login import current_user
from flask_app.models import Listing, User
import sass
import os

main = Blueprint('main', __name__)
print(os.listdir(os.getcwd()))

@main.route("/")
@main.route("/listings")
def index():
  sass.compile(dirname=('{}/flask_app/static/sass'.format(os.getcwd()), '{}/flask_app/static/css'.format(os.getcwd())), output_style='compressed')
  if not current_user.is_authenticated:
    return redirect(url_for('main.welcome'))
  listings = Listing.query.all()
  return render_template('index.html', title='Home', listings=listings)

@main.route("/welcome")
def welcome():
  return render_template('splash.html', title='Welcome')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/user/<username>")
def user_detail(username):
    user = User.query.filter_by(username=username).first()
    
    return render_template('user_detail.html', user=user, listings=user.listings)

@main.route("/csp_error_handling", methods=["POST"])
def report_handler():
    """
    Receives POST requests from the browser whenever the Content-Security-Policy 
    is violated. Processes the data and logs an easy-to-read version of the message
    in your console.
    """
    report = json.loads(request.data.decode())["csp-report"]

    # current_app.logger.info(json.dumps(report, indent=2))

    violation_desc = "\nViolated directive: %s, \nBlocked: %s, \nOriginal policy: %s \n" % (
        report["violated-directive"],
        report["blocked-uri"],
        report["original-policy"]
    )

    current_app.logger.info(violation_desc)
    return redirect(url_for("main.index"))

flask_app/users/routes.py
from flask import render_template, url_for, redirect, request, current_app, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, Listing
from flask_app.users.forms import RegistrationForm, LoginForm, UpdateForm

import qrcode
import qrcode.image.svg as svg

from io import BytesIO

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(username=form.username.data, email=form.email.data, password=hashed)
        db.session.add(user)
        db.session.commit()

        # return redirect(url_for('users.login'))
        session['reg_username'] = user.username

        return redirect(url_for('users.tfa'))
    
    return render_template('register.html', title='Register', form=form)


@users.route("/tfa")
def tfa():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

@users.route("/qr_code")
def qr_code():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))
    
    user = User.query.filter_by(username=session['reg_username']).first()

    session.pop('reg_username')

    img = qrcode.make(user.get_auth_uri(), image_factory=svg.SvgPathImage)

    stream = BytesIO()

    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return stream.getvalue(), headers


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('users.account'))

    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    username = current_user.username
    logout_user()
    current_app.logger.info('%s logged out successfully', username)
    return redirect(url_for('main.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateForm()
    listings = []
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.picture_url = form.picture_url.data
        db.session.commit()

        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.picture_url.data = current_user.picture_url
        listings = User.query.filter_by(id=current_user.id).first().listings
    
    return render_template('account.html', title='Account', form=form, listings=listings)

flask_app/templates/about.html
{% extends "base.html" %}
{% block nav_about %}active{% endblock %}
{% block content %}
    <div class="auth-header">
      <a href={{ url_for('main.index' )}}>
          <img src={{ url_for('static', filename='shpr.svg') }} alt="shpr logo"/>
      </a>
      <h1>about</h1>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href={{ url_for('main.index') }}>Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">About</li>
      </ol>
    </nav>
    <div>
        <h2 class="page-subtitle"><code>Secure, Full Stack eCommmerce Flask Application</code></h2>
        <p>
          Lorem ipsum.
        </p>
        <p><code>Open-Source Technologies</code></p>
        <ul>
          <li>Login/Registration w/ 2FA (Flask-Login)</li>
          <li>CSP (Flask-Talisman)</li>
          <li>CSRF-Protected Forms (Flask-WTForms)</li>
          <li>Hashed Passwords</li>
          <li>Bootstrap</li>
          <li>Font Awesome Icons</li>
        </ul>
    </div>
    
{% endblock %}

flask_app/templates/account.html
{% extends "base.html" %}
{% block nav_account %}active underline{% endblock %}
{% block content %}
    <div>
      <h1 class="page-title">Account</h1>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href={{ url_for('main.index') }}>Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Account</li>
      </ol>
    </nav>
    <div class="flexcol-center">
        {% if current_user.picture_url %}
            <img class="img-avatar" src={{ current_user.picture_url }} aria-label="profile image" height="64px"/>
        {% else %}
            <img class="img-avatar" src={{ url_for('static', filename='default-user.svg') }} aria-label="default profile image" height="64px"/>
        {% endif %}
        <h6>Email:<code> {{ current_user.email }}</code></h6>
        <h6>Username:<code> {{ current_user.username }}</code></h6>
    </div>
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg space-bottom-sm") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.picture_url.label(class="form-control-label") }}
                {{ form.picture_url(class="form-control form-control-lg space-bottom-sm") }}
                {% if form.picture_url.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.picture_url.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit(class="form-control") }}
            </div>
        </form>
    </div>
    <div>
        <h3>Your active listings:</h3>
    </div>
    <div class="grid">
    {% for listing in listings %}
        <article class="col-md-8 col-lg-5 listing-content-section box">
            <div>
                <div>
                    <a href={{ url_for('main.user_detail', username=listing.author.username) }}>{{ listing.author.username }}</a>
                    <small>on {{ listing.date.strftime('%B %d, %Y') }} listed:</small>
                </div>
                <div>
                    <img class="img-listing" src={{ listing.picture_url }} alt="item picture" />
                </div>
                <h5 class="sb__title">{{ listing.title }}</h5>
                <p>{{ listing.description }}</p>
            </div>
            <div class="flexrow-spacebetween">
                <p><code>Price: ${{ listing.price_in_pennies }}</code></p>
                <form action={{ url_for('listings.manage_listing', listing_id=listing.id) }}>
                    <button type="submit" class="btn sb__button" ><i class="fas fa-wrench"></i>&nbsp;Manage</button>
                </form>
            </div>
        </article>
    {% endfor %}
    </div>
{% endblock %}

flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Buy and sell, shipping included.">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <link rel="apple-touch-icon" sizes="180x180" href={{ url_for('static', filename='favicon_io/apple-touch-icon.png') }}>
    <link rel="icon" type="image/png" sizes="32x32" href={{ url_for('static', filename='favicon_io/favicon-32x32.png') }}>
    <link rel="icon" type="image/png" sizes="16x16" href={{ url_for('static', filename='favicon_io/favicon-16x16.png') }}>
    <link rel="manifest" href={{ url_for('static', filename='favicon_io/site.webmanifest') }}>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href={{ url_for('static', filename='css/custom.css') }}>
    <!-- <link rel="stylesheet" href="../static/custom.css"> -->
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed:300,400,700&display=swap" rel="stylesheet"> 
    <!-- <script src="https://use.fontawesome.com/df56271fe5.js"></script> -->
    <link href={{ url_for('static', filename='faweb/css/all.css') }} rel="stylesheet"> <!--load all styles -->
    <script defer src={{ url_for('static', filename='faweb/js/all.js') }}></script>
    {% if title %}
        <title>{{ title }} - SHPR</title>
    {% else %}
        <title>SHPR</title>
    {% endif %}
</head>
<body> 
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-inverse">
            <a class="navbar-brand" href={{ url_for('main.index' )}} style="margin-left:0.25rem">
                <img src={{ url_for('static', filename='shpr.svg') }} width="72px" alt="shpr logo"/>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-ellipsis-v fa-xs" style="color:#f5f5f5"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href={{ url_for('main.index') }} class="nav-link {% block nav_home %}{% endblock %}">home</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('main.about') }} class="nav-link {% block nav_about %}{% endblock %}">about</a>
                    </li>
                </ul>

                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item-not">
                        <form action={{ url_for('listings.create_listing') }}>
                            <button type="submit" class="btn sb__button">Sell an item<span></span>&nbsp;&rarr;</button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.account' )}} class="nav-link {% block nav_account %}{% endblock %}">
                            {% if current_user.picture_url %}
                            <img class="img-nav-avatar" src={{ current_user.picture_url }} alt="profile image" style="border-radius:0.75em;" height="32px"/>
                            {% else %}
                            <img class="img-nav-avatar" src={{ url_for('static', filename='default-user.svg') }} alt="default profile image" height="32px"/>
                            {% endif %}
                            {{ current_user.username }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('cart.user_cart' )}} class="nav-link {% block nav_cart %}{% endblock %}"><i class="fas fa-shopping-cart"></i>&nbsp;Cart({{current_user.cart | length}})</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.logout' )}} class="nav-link">Logout</a>
                    </li>
                </ul>

                {% else %}

                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('users.login' )}} class="nav-link {% block nav_login %}{% endblock %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.register' )}} class="nav-link {% block nav_register %}{% endblock %}">Register</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="container-fluid">
        <div class="row content-container">
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>






    {#{% block content %}{% endblock %}#}
    <!--
    <script src={{ url_for('static', filename='js/jquery.min.js' )}}></script>
    <script src={{ url_for('static', filename='js/popper.min.js' )}}></script>
    <script src={{ url_for('static', filename='js/bootstrap.min.js' )}}></script>
    -->
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!--<script src="https://kit.fontawesome.com/f69b7244e9.js" crossorigin="anonymous"></script>-->
</body>
</html>

flask_app/templates/cart.html
{% extends "base.html" %}
{% block nav_cart %}active underline{% endblock %}
{% block content %}
    <div>
        <h1 class="page-title">Your Cart</h1>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href={{ url_for('main.index') }}>Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Cart</li>
      </ol>
    </nav>
    <div>
        <h5>Customer ID: {{current_user.id}}</h5>
    </div>
    {% for listing in cart %}
        <article class="listing-content-section">
            <div>
                <div>
                    <a href={{ url_for('main.user_detail', username=listing.user.username) }}>{{ listing.user.username }}</a>
                </div>
                <div>
                    <img class="img-listing" src={{ listing.listing.picture_url }} alt="item picture" />
                </div>
                <h5 class="sb__title">{{ listing.listingtitle }}</h5>
                <p>{{ listing.listing.description }}</p>
            </div>
            <div class="flexrow-spacebetween">
                <p><code>Price: ${{ listing.listing.price_in_pennies }}</code></p>
                <form action={{ url_for('cart.remove_from_cart', listing_id=listing.id) }}>
                    <button type="submit" class="btn btn-danger sb__button sb__buy"><i class="fas fa-long-arrow-alt-left"></i><code>&nbsp;Remove</code></button>
                </form>
            </div>
        </article>
    {% endfor %}
{% endblock %}

flask_app/templates/index.html
{% extends "base.html" %}
{% block nav_home %}active underline{% endblock %}
{% block content %}
    <div>
        <h1 class="page-title">Explore</h1>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Home</li>
      </ol>
    </nav>
    <div class="grid">
    {% for listing in listings %}
        <article class="col-md-8 col-lg-4 listing-content-section">
            <div>
                <div>
                    <a href={{ url_for('main.user_detail', username=listing.author.username) }}>{{ listing.author.username }}</a>
                    <small>on {{ listing.date.strftime('%B %d, %Y') }} listed:</small>
                </div>
                <div>
                    <img class="img-listing" src={{ listing.picture_url }} alt="item picture" />
                </div>
                <h5 class="sb__title">{{ listing.title }}</h5>
                <p class="">{{ listing.description }}</p>
            </div>
            <div class="flexrow-spacebetween">
                <p><code>Price: ${{ listing.price_in_pennies }}</code></p>
                <form action={{ url_for('cart.add_to_cart', listing_id=listing.id) }}>
                    <button type="submit" class="btn sb__button">add to cart<span></span>&nbsp;&rarr;</button>
                </form>
            </div>
        </article>
    {% endfor %}
    </div>
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block nav_login %}active{% endblock %}
{% block content %}
    <div class="auth-header">
        <a href={{ url_for('main.index' )}}>
            <img src={{ url_for('static', filename='shpr.svg') }} alt="shpr logo"/>
        </a>
        <h1>login</h1>
    </div>
    <div>
        If you <b>don't</b> have an account, then <a href={{ url_for('users.register') }}>register.</a>
    </div>
    <div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>

            {% endif %}
            </div>
            <div>
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
            </div>
            <div>
                {{ form.token.label(class="form-control-label green-text") }}
                {{ form.token(class="form-control form-control-md") }}

                {% if form.token.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.token.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>

            {% endif %}
            </div>
            <br/>
            <div>
                {{ form.submit(class="btn sb__button ct") }}
            </div>
        </form>
    </div>
{% endblock %}

flask_app/templates/manage_listing.html
{% extends "base.html" %}
{% block content %}
    <div>
      <h1 class="page-title">Manage Listing</h1>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href={{ url_for('main.index') }}>Home</a></li>
        <li class="breadcrumb-item"><a href={{ url_for('users.account') }}>Account</a></li>
        <li class="breadcrumb-item active" aria-current="page">Manage Listing</li>
      </ol>
    </nav>
    {% if listing.picture_url %}
    <div>
      <article class="listing-content-section">
        <div>
            <div>
                <a href={{ url_for('main.user_detail', username=listing.author.username) }}>{{ listing.author.username }}</a>
                <small>on {{ listing.date.strftime('%B %d, %Y') }} listed:</small>
            </div>
            <div>
                <img class="img-listing" src={{ listing.picture_url }} alt="item picture" />
            </div>
            <h5 class="sb__title">{{ listing.title }}</h5>
            <p class="">{{ listing.description }}</p>
        </div>
        <div class="flexrow-spacebetween">
            <p><code>Price: ${{ listing.price_in_pennies }}</code></p>
        </div>
      </article>
    </div>
    {% endif %}
    <div>
       <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.item_name.label(class="form-control-label") }}
                {{ form.item_name(class="form-control form-control-lg space-bottom-sm") }}
                {% if form.item_name.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.item_name.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.item_desc.label(class="form-control-label") }}
                {{ form.item_desc(class="form-control form-control-lg space-bottom-sm") }}
                {% if form.item_desc.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.item_desc.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.price.label(class="form-control-label") }}
                {{ form.price(class="form-control form-control-lg space-bottom-sm") }}
                {% if form.price.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.price.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.item_picture_url.label(class="form-control-label") }}
                {{ form.item_picture_url(class="form-control form-control-lg space-bottom-sm") }}
                {% if form.item_picture_url.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.item_picture_url.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit(class="form-control") }}
            </div>
        </form>
    </div>
    
{% endblock %}

flask_app/templates/splash.html
{% extends "base.html" %}
{% block nav_home %}active{% endblock %}
{% block content %}
    <!--
    <div>
      <h1 class="sb__logo">Home</h1>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active">Home</li>
      </ol>
    </nav>
    -->
    <div class="banner">
        <h2 class="page-subtitle">Buy &amp; sell 🛒,<br/><br/>shipping included 💸.</h2>
        <form action={{ url_for('users.login') }}>
            <button type="submit" class="btn sb__button">login<span></span>&nbsp;&rarr;</button>
        </form>
        <br/>
        <form action={{ url_for('users.register') }}>
            <button type="submit" class="btn sb__button">join for free<span></span>&nbsp;&rarr;</button>
        </form>
    </div>
{% endblock %}

flask_app/templates/tfa.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1 class="page-title">Two-Factor Authenticator Enrollment</h2>
    </div>
    <p>
        This website requires mandatory 2FA enrollment. 
    </p>
    <!-- Registration Form: -->
    <p>
        Use the authenticator app to enroll with us! You will need to use this app to login in the future.
    </p>
    <div class="qr-container">
        <img src={{ url_for('users.qr_code') }} alt="QR Code for 2FA">
    </div>

    <div>
        When you're done, you can go to the <a href={{ url_for('users.login') }}>Login page</a>!
    </div>
{% endblock %}

flask_app/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1 class="page-title">{{ user.username }}'s Locker</h1>
    </div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href={{ url_for('main.index') }}>Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ user.username }}</li>
        </ol>
    </nav>
    <div>
        <div>
        {% if user.picture_url %}
            <img class="img-avatar" src={{ user.picture_url }} aria-label="profile image"/>
        {% else %}
            <img class="img-avatar" src={{ url_for('static', filename='default-user.svg') }} aria-label="default profile image"/>
        {% endif %}
        </div>
        <h3>{{ user.username }}'s Active Listings:</h3>
    </div>
    <div class="grid">
    {% for listing in listings %}
        <article class="col-md-8 col-lg-5 listing-content-section box">
            <div>
                <div>
                    <a href={{ url_for('main.user_detail', username=listing.author.username) }}>{{ listing.author.username }}</a>
                    <small>on {{ listing.date.strftime('%B %d, %Y') }} listed:</small>
                </div>
                <div>
                    <img class="img-listing" src={{ listing.picture_url }} alt="item picture" />
                </div>
                <h5 class="sb__title">{{ listing.title }}</h5>
                <p>{{ listing.description }}</p>
            </div>
            <div class="flexrow-spacebetween">
                <p><code>Price: ${{ listing.price_in_pennies }}</code></p>
                <form action={{ url_for('main.index') }}>
                    <button type="submit" class="btn btn-light sb__button">add to cart</button>
                </form>
            </div>
        </article>
    {% endfor %}
    </div>
{% endblock %}